# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 460535d1c4be0188045241dc5282e14053bf480af224773c85add85fe5b6bf449cb6f6fa230d230a174f7d4228ac82a809049547e3478ef8e30162d77589677e

test:
  secret_key_base: d05f2258f19dc14c88e12fad0588e8cf4515f4d139fc43202938032372b0d7df72788f75c42a68dfd0c1885d11cc8bc45ee301f2701fda9d61c477dfb2b2ec5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
